config/routes.rb
Rails.application.routes.draw do
  resources :flows

  devise_for :users
root "flows#index"
get "about" => "pages#about"

end

app/models/flow.rb
class Flow < ActiveRecord::Base

	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	# do_not_validate_attachment_file_type :image
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

	validates :description, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :flows

  validates :name, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end


end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
  before_action :set_flow, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]

  
  def index
    @flows = Flow.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 1)
  end

  
  def show
  end

  
  def new
    @flow = current_user.flows.build
  end

  
  def edit
  end

  
  def create
    @flow = current_user.flows.build(flow_params)
    if @flow.save
      redirect_to @flow, notice: 'Flow was successfully created.' 
          else
      render :new 
    end
  end

 
  def update
    if @flow.update(flow_params)
      redirect_to @flow, notice: 'Flow was successfully updated.'   
    else
      render :edit   
    end
  end

  
  def destroy
    @flow.destroy
    redirect_to flows_url, notice: 'Flow was successfully destroyed.'    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flow
      @flow = Flow.find(params[:id])
    end

    def correct_user

      @flow = current_user.flows.find_by(id: params[:id])
      redirect_to flows_path, notice: "Not authorize to edit this pin"  if @flow.nil?

    end




    # Never trust parameters from the scary internet, only allow the white list through.
    def flow_params
      params.require(:flow).permit(:description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/flows/_form.html.erb
<%= form_for @flow, html: { multipart: true }  do |f| %>
<% if @flow.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@flow.errors.count, "error") %> prohibited this flow from being saved:</h2>

  <ul>
    <% @flow.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>



<div class="form-group">
  
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>

</div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
  <% end %>

app/views/flows/edit.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Edit Flow </h3>
	</div>
	<div class="panel-body">

		<%= render 'form' %>
	</div>
	<div class="panel-footer">

		<%= link_to 'Show', @flow %> |
		<%= link_to 'Back', flows_path %>
	</div>

</div>

app/views/flows/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
  


<div id="flows" class="transitions-enabled">
  <% @flows.each do |flow| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(flow.image.url(:medium)), flow %>
      <div class="panel-body">
        <p><%= flow.description %></p>
        <p><strong><%= flow.user.name if flow.user %></strong></p>
        <% if flow.user == current_user %>
          <div class="actions">
            <%= link_to edit_flow_path(flow) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
            <% end %>
            <%= link_to flow, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            Delete
            <% end %>
          </div>  
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center"><%= will_paginate @posts, renderer: BootstrapPagination::Rails %></div>

app/views/flows/new.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">

		<h3 class="panel-title">New flow</h3>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
	<%= link_to 'Back', flows_path %>
	</div>
</div>

app/views/flows/show.html.erb
<%= link_to 'Back', flows_path %>

<div class="row">

	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @flow.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p><%= @flow.description %></p>
				<p><strong><%= @flow.user.name if @flow.user %></strong></p>

				<% if @flow.user == current_user %>
					<%= link_to edit_flow_path(@flow) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
            <% end %>
				<% end %>
			</div>
		</div>
	</div>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <!-- <a class="navbar-brand" href="#">It's Flowing</a> -->
      <%= link_to "It's Flowing!", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
     <!--  <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to new_flow_path do %>
          <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </li>
        <li><%= link_to "Account Settings", edit_user_registration_path%></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

        <% else %>

        <li><%= link_to "Sign in", new_user_session_path, class:"navLinks" %></li>

        <% end %>
      </ul> 



    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>IT'S FLOWING</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render "layouts/header" %>

	<div class="container"> 
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert, alert-info") %>

		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>It's Flowing!</h1>
	<!-- <h4><i>It's coming soon</i></h4> -->
	

	

	<p>
		<%= link_to "Log in ", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up ", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p> 
	


</div>



<!-- <div class="mainDescription">
	<p><span class="description">CREATE. SHARE. INSPIRE OTHERS.
		BE INSPIRED BY OTHERS. CREATE. SHARE. INSPIRE OTHERS.
		BE INSPIRED BY OTH.... well, I guess you get the idea.</span></p>
	</br>

	<p><span class="mainName">IT'S FLOWING </span>is about that. It's a network for artists of all disciplines, that want or need a source of inspiration. It's about artists connecting and helping each other make their art grow. It's about hard work, constructive feedback, and most importantly...no BS.</p>

</div> -->



app/views/pages/about.html.erb
<h1>About It's Flowing</h1>
</br>
<p>CREATE. SHARE. INSPIRE OTHERS.
BE INSPIRED BY OTHERS. CREATE. SHARE. INSPIRE OTHERS.
BE INSPIRED BY OTH.... well, I guess you get the idea.</p>
</br>

<p>IT'S FLOWING is about that. It's a network for artists of all disciplines, that want or need a source of inspiration (trigger). It's about artists connecting and helping each other make their art grow. It's about hard work, constructive feedback, and most importantly...no BS.</p>
</br>

<p>
Example: Veronica is a writer. She wrote a short story and shared it on Flowing. Fred is a photographer. He read Veronica’s short story, and inspired him for a picture idea based on that story. He shared the picture on Flowing and linked it to Veronica’s story. Thomas is a painter. After reading Veronica’s story, he made a painting inspired on it. And of course, he shared it on Flowing. Anna is a comics artist. She liked Veronica’s story, and both Fred and Thomas visuals inspired on it. So she gets inspired by all that and transform it in a short graphic novel. And shared it on Flowing. Lucas is a composer. He created a piece inspired on Veronica and Thomas’ works. He shared it on Flowing. Agnes is a filmmaker. She contacted Veronica, and made a short film based on her story. She also contacted Lucas and asked him to use his music in it. 

</p>
